[tool.poetry]
name = "jdk4py"
# Poetry requires this but we do not use it.
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.10"

[tool.poetry.dev-dependencies]
mypy = "*"
ruff = "*"
setuptools = "*"
twine = "*"
wheel = "*"

[tool.mypy]
strict = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
